stages:
  - build
  - test

build_job:
  stage: build
  script:
    - echo "building on MY SERVER: $(hostname)"
    - mkdir -p dist
    - echo "app version 1.0" > dist/app.txt
  artifacts:
    paths:
      - dist/

test_job:
  stage: test
  script:
    - echo "running tests"
    - cat dist/app.txt

